repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        verbose: true

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        verbose: true
        additional_dependencies:
          - flake8-bugbear==21.4.3
          - flake8-implicit-str-concat==0.2.0
        args: [--config=hook_configs/.flake8]

  - repo: git://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        verbose: true
        args: [--settings-pat=hook_configs/.isort.cfg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        verbose: true
        additional_dependencies:
          - 'pydantic'
        args: [--config=hook_configs/mypy.ini]
